# Site Settings (FOR LOCAL)
title: David Walker
email: davidw1427@gmail.com
description: >
  Musings of a web developer.
baseurl: "/ga_blog"  
url: "davidw-developer.github.io/ga_blog"
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM